 # .github/workflows/deploy.yaml

 name: Deploy Services to Google Cloud

 on:
   push:
     branches:
       - main

 env:
   PROJECT_ID: fraud-digest-app-v2-469310
   REGION: europe-west1

 jobs:
   # JOB 1: Deploy the Backend Cloud Function
   deploy-backend:
     name: Deploy Backend Function
     runs-on: ubuntu-latest

     permissions:
       contents: 'read'
       id-token: 'write'

     steps:
       - name: Checkout repository
         uses: actions/checkout@v4

       - name: Authenticate to Google Cloud
         uses: google-github-actions/auth@v2
         with:
           workload_identity_provider: 'projects/963241002796/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
           service_account: 'github-actions-deployer@fraud-digest-app-v2-469310.iam.gserviceaccount.com'

       - name: Deploy Cloud Function
         uses: google-github-actions/deploy-cloud-functions@v2
         with:
           name: fraud-analysis-processor
           region: ${{ env.REGION }}
           runtime: python310
           source_dir: ./backend
           entry_point: main
           trigger_topic: analysis-requests
           gen2: true
           build_worker_pool: projects/${{ env.PROJECT_ID }}/locations/${{ env.REGION }}/workerPools/europe-west1-pool
           docker_registry: artifact-registry

   # Uncomment the following job to deploy the frontend Streamlit app when ready
   # JOB 2: Deploy the Frontend Streamlit App (we will enable this later)
   # deploy-frontend:
   #   name: Deploy Frontend to Cloud Run
   #   runs-on: ubuntu-latest
   #   needs: deploy-backend # Run after backend is deployed
   #
   #   permissions:
   #     contents: 'read'
   #     id-token: 'write'
   #
   #   steps:
   #     - name: Checkout repository
   #       uses: actions/checkout@v4
   #
   #     - name: Authenticate to Google Cloud
   #       uses: google-github-actions/auth@v2
   #       with:
   #         workload_identity_provider: 'projects/963241002796/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
   #         service_account: 'github-actions-deployer@fraud-digest-app-v2-469310.iam.gserviceaccount.com'
   #
   #     - name: Set up Cloud SDK
   #       uses: google-github-actions/setup-gcloud@v2
   #
   #     - name: Build and push Docker image
   #       run: |-
   #         docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/fraud-digest-repo/the-fraud-digest-weekly-app:latest .
   #         gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev
   #         docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/fraud-digest-repo/the-fraud-digest-weekly-app:latest
   #
   #     - name: Deploy to Cloud Run
   #       run: |-
   #         gcloud run deploy fraud-digest-weekly-app \
   #           --image=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/fraud-digest-repo/the-fraud-digest-weekly-app:latest \
   #           --region=${{ env.REGION }} \
   #           --platform=managed \
   #           --quiet
