# .github/workflows/deploy.yaml

name: Deploy Services to Google Cloud

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: fraud-digest-app-v2-469310
  REGION: europe-west1
  # --- Backend Config ---
  BACKEND_SERVICE_NAME: fraud-analysis-processor-v2
  BACKEND_IMAGE_NAME: fraud-digest-backend
  # --- Trigger Config ---
  TOPIC_NAME: analysis-requests
  TRIGGER_NAME: fraud-analysis-processor-v2-trigger
  TRIGGER_SA: eventarc-trigger-sa@fraud-digest-app-v2-469310.iam.gserviceaccount.com

jobs:
  deploy-backend:
    name: Build and Deploy Backend
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/963241002796/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-deployer@fraud-digest-app-v2-469310.iam.gserviceaccount.com'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Build and Push Backend Docker Image
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/fraud-digest-repo/${{ env.BACKEND_IMAGE_NAME }}:latest -f backend/Dockerfile backend

          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/fraud-digest-repo/${{ env.BACKEND_IMAGE_NAME }}:latest

      - name: Deploy Backend Image to Cloud Run
        run: |
          gcloud run deploy ${{ env.BACKEND_SERVICE_NAME }} \
            --project=${{ env.PROJECT_ID }} \
            --region=${{ env.REGION }} \
            --image=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/fraud-digest-repo/${{ env.BACKEND_IMAGE_NAME }}:latest \
            --ingress=internal \
            --allow-unauthenticated \
            --memory=512Mi \
            --quiet

      - name: Create or Update Eventarc Trigger
        run: |
          gcloud eventarc triggers describe ${{ env.TRIGGER_NAME }} \
            --project=${{ env.PROJECT_ID }} \
            --location=${{ env.REGION }} && \
          echo "Trigger already exists. No action needed." || \
          gcloud eventarc triggers create ${{ env.TRIGGER_NAME }} \
            --project=${{ env.PROJECT_ID }} \
            --location=${{ env.REGION }} \
            --destination-run-service=${{ env.BACKEND_SERVICE_NAME }} \
            --destination-run-region=${{ env.REGION }} \
            --event-filters="type=google.cloud.pubsub.topic.v1.messagePublished" \
            --transport-topic=${{ env.TOPIC_NAME }} \
            --service-account=${{ env.TRIGGER_SA }}
