# .github/workflows/deploy.yaml

name: Deploy Services to Google Cloud

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: fraud-digest-app-v2-469310
  REGION: europe-west1
  SERVICE_NAME: fraud-analysis-processor-v2 # Using v2 to ensure a clean deploy
  TOPIC_NAME: analysis-requests
  TRIGGER_NAME: fraud-analysis-processor-v2-trigger
  TRIGGER_SA: eventarc-trigger-sa@fraud-digest-app-v2-469310.iam.gserviceaccount.com

jobs:
  deploy-backend:
    name: Deploy Backend Function and Trigger
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/963241002796/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-deployer@fraud-digest-app-v2-469310.iam.gserviceaccount.com'

      - name: Deploy Cloud Function
        id: deploy_function
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          runtime: python310
          source_dir: ./backend
          entry_point: main
          gen2: true
          ingress_settings: 'ALLOW_INTERNAL_ONLY'
          all_traffic_on_latest_revision: true

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@main

      - name: Create or Update Eventarc Trigger
        run: |
          gcloud eventarc triggers describe ${{ env.TRIGGER_NAME }} \
            --project=${{ env.PROJECT_ID }} \
            --location=${{ env.REGION }} && \
          echo "Trigger already exists. No action needed." || \
          gcloud eventarc triggers create ${{ env.TRIGGER_NAME }} \
            --project=${{ env.PROJECT_ID }} \
            --location=${{ env.REGION }} \
            --destination-run-service=${{ env.SERVICE_NAME }} \
            --destination-run-region=${{ env.REGION }} \
            --transport-topic=${{ env.TOPIC_NAME }} \
            --service-account=${{ env.TRIGGER_SA }}

